### ISSUE TITLE
Mask layers when uploading to pulp

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/raas#19]
Mask the red hat layers when uploading to pulp. `mask_id` should be passed during `_import_upload()`. See http://pulp-docker.readthedocs.org/en/latest/tech-reference/importer.html

Example call from CLI:

```
POST request to /pulp/api/v2/repositories/saas-saas-web/actions/import_upload/ with parameters
"override_config": {
    "mask_id": "bef54b8f8a2fdd221734f1da404d4c0a7d07ee9169b1443a338ab54236c8c91a"},
    "unit_type_id": "docker_image",
    "upload_id": "e4530fc7-801f-49c5-a73b-308c7beafff5",
    "unit_key": {},
    "unit_metadata": {}
}
```

**Comment by pschiffe** [comment]
We need to figure out getting the Red Hat image IDs.

**Comment by aweiteka** [comment]
@pschiffe the short-term plan is to grab RH image IDs from the configuration repo of crane files.

**Comment by pschiffe** [comment]
Great, thanks for the update.
