### ISSUE TITLE
Package as RPM

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/raas#24]
I know nothing about RPM packaging. We need this to run on RHEL(7?)

**Comment by pschiffe** [comment]
I can create RPM package, but wouldn't be better to distribute this directly as docker image? We could tune the current dockerfile to be production ready and point users to the https://registry.hub.docker.com/u/aweiteka/raas/ .

**Comment by aweiteka** [comment]
@pschiffe I agree Docker packaging is a good format and it will be used. Some users have asked for RPM. I'll ask if a Docker image will work or if they really need RPM.

**Comment by pschiffe** [comment]
Thanks, please do. I would like to keep ways of distribution to minimum.

**Comment by aweiteka** [comment]
Feedback so far has not indicated a need for RPM. Closing.
