### ISSUE TITLE
add -v|--verbose flag to change stdout verbosity

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/raas#36]
The processes that use raas will be relying on stdout to drive other processes. Interactive human use should still provide stdout progress. Add `-v` or `--verbose` flag for interactive stdout. Otherwise the default should be the following:
- `pulp-upload`: output `<image/name>`
- `publish`: output `docker pull ...` URL, e.g. `registry-<isv>.rhcloud.com/<image/name>`
- `status -a APP_NAME`: output `docker pull ...` URL, e.g. `registry-<isv>.rhcloud.com/<image/name>`

**Comment by pschiffe** [comment]
Let's try opposite approach here. Keep regular stdout as default, and add --terse option to suppress regular output and print only docker commands, etc..
