### ISSUE TITLE
pulp-upload should not require Openshift domain name

### ISSUE THREAD

**Issue by navidshaikh** [aweiteka/raas#67]
Pulp upload command

```
raas pulp-upload <isv> /run/docker_uploads/<some-image>.tar
```

should not require Openshift domain name to be specified, however the upload step is failing with following error message

```
2015-03-09 10:03:22,559 - PULP-UPLOAD - root - ERROR - Openshift domain name is missing. Please specify it with "--oodomain" option or in config file
2015-03-09 10:03:22,559 - PULP-UPLOAD - root - CRITICAL - Failed to initialize raas: Missing openshift domain name
```

**Comment by aweiteka** [comment]
We need to support `pulp-upload` running before `setup`. So `pulp-upload` should not require a pre-configured config file. If `pulp-upload` is run before `setup` we can either populate an empty cfg section for that ISV or omit writing the config altogether.

**Comment by aweiteka** [comment]
Workaround:
1. Use local config file. Edit raas.cfg, add a section for ISV which includes openshift domain
2. Run `raas` from the directory with the local cfg file with the `--nocommit` option:

```
raas --nocommit pulp-upload <isv> <file>.tar
```
