### ISSUE TITLE
Explicitly call aws to get bucket_url

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/raas#71]
We are [deriving the redirect_url](https://github.com/aweiteka/raas/blob/master/raas.py#L1135). This causes a `301 response missing Location header` error when docker pull-ing from non-default AWS regions. We should be querying the AWS API for this value.

**Comment by pschiffe** [comment]
Current status of this feature is, that we support amazon regions, but only for local buckets and for shared buckets with admin privileges. Shared bucket with only read+write permissions don't allow us to query for it's location, so we are unable to determine the URL of bucket. If getting location of bucket fails, we assume that the bucket is in the main US region.

Another issue is with Frankfurt amazon region - we are unable to query buckets there. Issue is on the amazon side, see https://github.com/boto/boto/issues/2741
